#! /bin/sh

error() {
    echo $*
    exit 2
}

dns_servers="aRootServer bRootServer cRootServer \
             dnsCom dnsOrg dnsHr hr2 \
             dnsFer \
             dnsTel dnsZpm"

hosts="mm www pc zpmMail"

if test $# -eq 1; then
    eid=$1
else
    eid=`himage -e aRootServer`
    if test $? -ne 0; then
        exit 1
    fi
fi

cd DNS_files

for i in $dns_servers
do
    himage ${i}@${eid} pgrep -q named
    if test $? -eq 0; then
        echo "$i: ok"
    else
        echo "$i: named is not running"
    fi
done

