#! /bin/sh

for h in mm pc
do
  echo "*****"
  echo "* Test from $h:"
  echo "*"
  himage $h host -t ANY www.tel.fer.hr
  echo ""
  himage $h host -t ANY pc.zpm.fer.hr
  echo ""
  himage $h host -t NS org
  echo ""
  himage $h host -t NS hr
  echo ""
done

