#! /bin/sh

echo dnsTel:
himage dnsTel delv @127.0.0.1 www.tel.fer.hr A +multiline

echo dnsTel:
himage dnsTel delv @127.0.0.1 www.zpm.fer.hr A +multiline

echo dnsZpm:
himage dnsTel delv @127.0.0.1 www.zpm.fer.hr A +multiline

echo dnsZpm:
himage dnsZpm delv @127.0.0.1 www.tel.fer.hr A +multiline

# echo mm:
# himage mm delv @10.0.9.2 www.tel.fer.hr A +multiline

